#!/usr/bin/env sh
set -e

BLUE='\033[34m'
GREEN='\033[32m'
RESET='\033[39m'


printf "\n${BLUE}------------------${RESET}\n"
printf "${BLUE}Step 1: pnpm check${RESET}\n"
printf "${BLUE}------------------${RESET}\n"


pnpm check
